config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, controllers: {
    sessions:      'public/sessions',
    passwords:     'public/passwords',
    registrations: 'public/registrations'
  }
  devise_for :admin, controllers: {
    sessions:      'admin/sessions',
    passwords:     'admin/passwords',
    registrations: 'admin/registrations'
  }
  namespace :admin do
    root to: 'homes#top'
    resources :items, except: [:destroy,]
    resources :customers, only: [:index, :show, :edit, :update,]
    resources :orders, only: [:show]
  end
  scope module: :public do
   root to: 'homes#top'
   get "/about" => "homes#about", as: "about"
   patch "/customers/withdraw" => "customers#withdraw"
   get "/customers/my_page" => "customers#show"
   get "/customers/check" => "customers#check"
   delete "/cart_items/destroy_all" => "cart_items#destroy_all"
   post "/orders/confirm" => "orders#confirm"
   get "/orders/complete" => "orders#complete"
   resources :customers,only: [:edit, :update,]
   resources :items,only: [:index, :show,]
   resources :cart_items,only: [:index, :update, :create, :destroy,]
   resources :orders,only: [:new, :create, :show, :index]
  end

end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items
  has_many :order_details
  attachment :image
  def add_tax_price
    (self.price * 1.10).round
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def index
   @items = Item.page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
   @item = Item.find(params[:id])
   @item.update(item_params)
   redirect_to admin_item_path(@item.id)
  end

  private

  def item_params
    params.require(:item).permit(:image, :name, :introduction, :price)
  end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<div class="container">
 <h3 class="offset-1 my-5 text title-text">商品編集</h3>

 <div class="offset-2">
 <%= form_with model: @item, url: admin_item_path(@item.id), local:true do |f| %>
  <div class="row mt-5 light-text">
    <label class="col-md-2 mr-2 text">商品画像</label>
    <%= f.attachment_field :image, class: 'col-md-5' %>
  </div>
  <div class="row mt-2 light-text">
    <label class="col-md-2 mr-2 text">商品名</label>
    <%= f.text_field :name, autofocus: true, class: 'col-md-3' %>
  </div>
  <div class="row mt-3 light-text">
    <label class="col-md-2 mr-2 text">商品説明<br/><br/><br/><br/></label>
    <%= f.text_area :introduction, autofocus: true, class: 'col-md-3' %>
  </div>
  <div class="row mt-2 light-text">
    <label class="col-md-2 mr-2 text">税抜価格</label>
    <%= f.text_field :price, autofocus: true, class: 'col-md-3 mr-1' %>円
  </div>
  <div class="row mt-4 text">
    <label class="col-md-2 mr-2"></label>
    <%= f.submit "変更を保存", class: 'ml-4 col-md-2 btn btn-success' %>
  </div>
 <% end %>
 </div>
</div>

app/views/admin/items/index.html.erb
<div class="container my-5">
 <div class="row">
  <div class="col-6">
   <h3 class="offset-1 title-text text">商品一覧</h3>
  </div>
  <div class="col-6">
   <div class="text-right"><%= link_to (new_admin_item_path) do %><i class="fas fa-plus-circle fa-3x text-dark"></i><% end %></div>
  </div>
 </div>

 <div class="row mt-3">
  <table class="table table-hover">
   <thead>
    <tr class="table-active text">
     <th>商品ID</th>
     <th>商品名</th>
     <th>税抜価格</th>
     <th></th>
     <th></th>
    </tr>
   </thead>

   <tboy>
    <% @items.each do |item| %>
    <tr class="light-text">
     <td><%= item.id %></td>
     <td><%= link_to item.name, admin_item_path(item.id), class: 'text-dark' %></td>
     <td><%= item.price %></td>
     <td></td>
     <td></td>
    </tr>
    <% end %>
   </tboy>
  </table>
  <div class=""><%= paginate @items %></div>
 </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
 <h3 class="offset-1 my-5 text title-text">商品新規登録</h3>

 <div class="offset-2">
 <%= form_with model: @item, url: admin_items_path, local:true do |f| %>
  <div class="row mt-5 light-text">
    <label class="col-md-2 mr-2 text">商品画像</label>
    <%= f.attachment_field :image, class: 'col-md-5' %>
  </div>
  <div class="row mt-2 light-text">
    <label class="col-md-2 mr-2 text">商品名</label>
    <%= f.text_field :name, autofocus: true, placeholder: "商品名", class: 'col-md-3' %>
  </div>
  <div class="row mt-3 light-text">
    <label class="col-md-2 mr-2 text">商品説明<br/><br/><br/><br/></label>
    <%= f.text_area :introduction, autofocus: true, placeholder: "ここに商品名を記述します", class: 'col-md-3' %>
  </div>
  <div class="row mt-2 light-text">
    <label class="col-md-2 mr-2 text">税抜価格</label>
    <%= f.text_field :price, autofocus: true, placeholder: "1000", class: 'col-md-3 mr-1' %>円
  </div>
  <div class="row mt-2 text">
    <label class="col-md-2 mr-2"></label>
    <%= f.submit "新規登録", class: 'ml-4 col-md-2 btn btn-success' %>
  </div>
 <% end %>
 </div>
</div>

app/views/admin/items/show.html.erb
<div id="container">
 <div class="row">
  <h3 class="offset-2 p-5 title-text text">商品詳細</h3>
 </div>

 <div class="row">
  <div class="offset-2 pl-5 mt-5 col-3">
   <div><%= attachment_image_tag @item, :image, :fill, 300, 200, fallback: "no_image.jpg", size: "300x200" %></div>
  </div>
  <div class="mt-5 col-md-1">
    <p>商品名</p>
    <p></p>商品説明</p>
    <p>税込価格<br/>(税抜価格)</p>
  </div>
  <div class="mt-5 col-md-6">
    <p><%= @item.name %></p>
    <p><%= @item.introduction %></p>
    <p><%= @item.add_tax_price.to_s(:delimited) %>(<%= @item.price %>) 円
  </div>
  <div class="mx-auto mt-5"><%= link_to "編集する", edit_admin_item_path, class: "btn-lg btn-success" %></div>
 </div>
</div>