config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, controllers: {
    sessions:      'public/sessions',
    passwords:     'public/passwords',
    registrations: 'public/registrations'
  }
  devise_for :admin, controllers: {
    sessions:      'admin/sessions',
    passwords:     'admin/passwords',
    registrations: 'admin/registrations'
  }
  namespace :admin do
    root to: 'homes#top'
    resources :items, except: [:destroy,]
    resources :customers, only: [:index, :show, :edit, :update,]
    resources :orders, only: [:show]
  end
  scope module: :public do
   root to: 'homes#top'
   get "/about" => "homes#about", as: "about"
   patch "/customers/withdraw" => "customers#withdraw"
   get "/customers/my_page" => "customers#show"
   get "/customers/check" => "customers#check"
   delete "/cart_items/destroy_all" => "cart_items#destroy_all"
   post "/orders/confirm" => "orders#confirm"
   get "/orders/complete" => "orders#complete"
   resources :customers,only: [:edit, :update,]
   resources :items,only: [:index, :show,]
   resources :cart_items,only: [:index, :update, :create, :destroy,]
   resources :orders,only: [:new, :create, :show, :index]
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  enum is_active: { 有効: true, 退会: false }

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
 before_action :authenticate_admin!

  def index
   @customers = Customer.page(params[:page])
  end

  def show
   @customer = Customer.find(params[:id])
  end

  def edit
   @customer = Customer.find(params[:id])
  end

  def update
   @customer = Customer.find(params[:id])
   @customer.update(customer_params)
   redirect_to admin_customer_path(@customer.id)
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email,)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
 <div class="row md-5">
  <h3 class="offset-1 my-4"><%= @customer.last_name + @customer.first_name %>さんの会員情報編集</h3>
  <div class="col-12">
   <%= form_with model: @customer, url: admin_customer_path(@customer.id), local:true do |f| %>
   <div class="form-group row">
    <%= f.label :id, "会員", class: 'col-form-label col-3 font-weiht-bold' %>
    <div class="col-8"><%= f.label :id, @customer.id, class: 'ml-4' %></div>
   </div>

   <div class="form-group row">
     <%= f.label :first_name, "氏名", class: 'col-form-label col-3 font-weiht-bold' %>
     <div class="col-4"><%= f.text_field :last_name, autofocus: true, class: 'form-control' %></div>
     <div class="col-4"><%= f.text_field :first_name, autofocus: true, class: 'form-control' %></div>
   </div>

   <div class="form-group row">
     <%= f.label :first_name_kana,"フリガナ", class: 'col-form-label col-3 font-weiht-bold' %>
     <div class="col-4"><%= f.text_field :last_name_kana, autofocus: true, class: 'form-control' %></div>
     <div class="col-4"><%= f.text_field :first_name_kana, autofocus: true, class: 'form-control' %></div>
   </div>

   <div class="form-group row">
     <%= f.label :postal_code, "郵便番号", class: 'col-form-label col-3 font-weiht-bold' %>
     <div class="col-4"><%= f.text_field :postal_code, autofocus: true, class: 'form-control' %></div>
   </div>

   <div class="form-group row">
     <%= f.label :address, "住所", class: 'col-form-label col-3 font-weiht-bold' %>
     <div class="col-4"><%= f.text_field :address, autofocus: true, class: 'form-comtrol' %></div>
   </div>

   <div class="form-group row">
     <%= f.label :telephone_number, "電話番号", class: 'col-form-label col-3 font-weiht-bold' %>
     <div class="col-4"><%= f.text_field :telephone_number, autofocus: true, class: 'form-comtrol' %></div>
   </div>

   <div class="form-group row">
     <%= f.label :email, "メールアドレス", class: 'col-form-label col-3 font-weiht-bold' %>
     <div class="col-4"><%= f.text_field :email, autofocus: true, class: 'form-comtrol' %></div>
   </div>

   <div class="form-group row mt-4">
     <div class="col-3"></div>
     <div class="col-4"><%= f.submit "変更を保存", class: 'btn-lg btn-success w-50' %></div>
   </div>
   <% end %>
  </div>
 </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
 <div class="row mb-4">
  <div class="col-12">
   <h3 class="my-5 text title-text">会員一覧</h3>
   <div class="row">
    <div class="col-12 mx-auto">
     <table class="table table-hover">
      <thead>
       <tr class="table-active text">
        <th>会員ID</th>
        <th>氏名</th>
        <th>メールアドレス</th>
        <th>ステータス</th>
        <th></th>
       </tr>
      </thead>

      <tboy>
       <% @customers.each do |customer| %>
        <tr class="light-text">
         <td><%= customer.id %></td>
         <td><%= link_to customer.last_name + customer.first_name, admin_customer_path(customer.id), class: 'text-dark' %></td>
         <td><%= customer.email %></td>
         <td><%= customer.is_active %></td>
         <td></td>
        </tr>
       <% end %>
      </tboy>
     </table>
     <div class="mx-auto"><%= paginate @customers %></div>
    </div>
   </div>
  </div>
 </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
 <div class="row">
  <h4 class="col-4 m-4"><%= @customer.last_name + @customer.first_name %>さんの会員詳細</h4>
 </div>
 <div class="row md-5">
   <div class="col-9">
     <table class="table table-borderless">
      <tr>
       <th>会員ID</th>
       <td><%= @customer.id %></td>
      </tr>
      <tr>
       <th>氏名</p>
       <td><%= @customer.last_name + @customer.first_name %></td>
      </tr>
      <tr>
       <th>フリガナ</th>
       <td><%= @customer.last_name_kana + @customer.first_name_kana %></td>
      </tr>
      <tr>
       <th>郵便番号</th>
       <td><%= @customer.postal_code %></td>
      </tr>
      <tr>
       <th>住所</th>
       <td><%= @customer.address %></td>
      </tr>
      <tr>
       <th>電話番号</th>
       <td><%= @customer.telephone_number %></td>
      </tr>
      <tr>
       <th>メールアドレス</th>
       <td><%= @customer.email %></td>
      </tr>
      <tr>
       <th></th>
       <td class="pt-4">
        <%= link_to "編集する", edit_admin_customer_path(@customer.id), class: 'btn btn-success' %>
        <%= link_to '注文履歴一覧を見る', admin_root_path, class: 'btn btn-primary offset-2' %>
       </td>
      </tr>
     </table>
   </div>
 </div>
</div>