config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, controllers: {
    sessions:      'public/sessions',
    passwords:     'public/passwords',
    registrations: 'public/registrations'
  }
  devise_for :admin, controllers: {
    sessions:      'admin/sessions',
    passwords:     'admin/passwords',
    registrations: 'admin/registrations'
  }
  namespace :admin do
    root to: 'homes#top'
    resources :items, except: [:destroy,]
    resources :customers, only: [:index, :show, :edit, :update,]
    resources :orders, only: [:show]
  end
  scope module: :public do
   root to: 'homes#top'
   get "/about" => "homes#about", as: "about"
   patch "/customers/withdraw" => "customers#withdraw"
   get "/customers/my_page" => "customers#show"
   get "/customers/check" => "customers#check"
   delete "/cart_items/destroy_all" => "cart_items#destroy_all"
   post "/orders/confirm" => "orders#confirm"
   get "/orders/complete" => "orders#complete"
   resources :customers,only: [:edit, :update,]
   resources :items,only: [:index, :show,]
   resources :cart_items,only: [:index, :update, :create, :destroy,]
   resources :orders,only: [:new, :create, :show, :index]
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  enum method_of_payment: { クレジットカード: 1, 銀行振込: 2 }
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def show
   @order = Order.find(params[:id])
   @order_details = @order.order_details
   @sum = 0
   @order_details.each do |order_detail|
     @sum = @sum+order_detail.price*order_detail.order_amount
   end
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<div class="container my-5">
  <div class="row">
    <div class="offset-1 text-center">
      <h3 class="title-sub-text text">
        注文履歴詳細
      </h3>
    </div>
  </div>

  <div class="row mt-5">
    <div class="col-6">
      <table class="table table-borderless">
        <tbody>
          <tr>
            <td>購入者</td>
            <td>
              <%= link_to @order.name, admin_customer_path(@order.customer), class: "text-dark" %>
            </td>
          </tr>
          <tr>
            <td>注文日</td>
            <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
          </tr>
          <tr>
            <td>配送先</td>
            <td>
              〒<%= @order.zip_code %>
                <%= @order.address %><br>
                <%= @order.name %>
            </td>
          </tr>
          <tr>
            <td>支払方法</td>
            <td><%= @order.method_of_payment %></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

  <div class="row mt-5">
    <div class="col-9">

      <table class="table table-borderless table-hover">
        <thead class="table-active">
          <tr class="text">
            <th>商品名</th>
            <th>単価(税込)</th>
            <th>個数</th>
            <th>小計</th>
          </tr>
        </thead>
        <tbody>
          <% @order_details.each do |order_details| %>
          <tr class="light-text">
            <td><%= order_details.item.name %></td>
            <td><%= order_details.price %></td>
            <td><%= order_details.order_amount %></td>
            <td><%= order_details.price * order_details.order_amount %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class="col-3">
      <table class="table table-borderless">
        <tbody>
          <tr>
            <td>商品合計</td>
            <td ><%= @sum %></td>
          </tr>
          <tr>
            <td>送料</td>
            <td><%= @order.postage %>円</td>
          </tr>
          <tr>
            <td>請求合計金額</td>
            <td><%= @order.total_payment %>円</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>