config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, controllers: {
    sessions:      'public/sessions',
    passwords:     'public/passwords',
    registrations: 'public/registrations'
  }
  devise_for :admin, controllers: {
    sessions:      'admin/sessions',
    passwords:     'admin/passwords',
    registrations: 'admin/registrations'
  }
  namespace :admin do
    root to: 'homes#top'
    resources :items, except: [:destroy,]
    resources :customers, only: [:index, :show, :edit, :update,]
    resources :orders, only: [:show]
  end
  scope module: :public do
   root to: 'homes#top'
   get "/about" => "homes#about", as: "about"
   patch "/customers/withdraw" => "customers#withdraw"
   get "/customers/my_page" => "customers#show"
   get "/customers/check" => "customers#check"
   delete "/cart_items/destroy_all" => "cart_items#destroy_all"
   post "/orders/confirm" => "orders#confirm"
   get "/orders/complete" => "orders#complete"
   resources :customers,only: [:edit, :update,]
   resources :items,only: [:index, :show,]
   resources :cart_items,only: [:index, :update, :create, :destroy,]
   resources :orders,only: [:new, :create, :show, :index]
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  enum is_active: { 有効: true, 退会: false }

end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items
  has_many :order_details
  attachment :image
  def add_tax_price
    (self.price * 1.10).round
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  enum method_of_payment: { クレジットカード: 1, 銀行振込: 2 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :item
  belongs_to :order
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
 before_action :authenticate_admin!

  def index
   @customers = Customer.page(params[:page])
  end

  def show
   @customer = Customer.find(params[:id])
  end

  def edit
   @customer = Customer.find(params[:id])
  end

  def update
   @customer = Customer.find(params[:id])
   @customer.update(customer_params)
   redirect_to admin_customer_path(@customer.id)
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email,)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
   @orders = Order.page(params[:page])
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def index
   @items = Item.page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
   @item = Item.find(params[:id])
   @item.update(item_params)
   redirect_to admin_item_path(@item.id)
  end

  private

  def item_params
    params.require(:item).permit(:image, :name, :introduction, :price)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def show
   @order = Order.find(params[:id])
   @order_details = @order.order_details
   @sum = 0
   @order_details.each do |order_detail|
     @sum = @sum+order_detail.price*order_detail.order_amount
   end
  end
end

app/controllers/admin/passwords_controller.rb
# frozen_string_literal: true

class Admin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  def destroy
    sign_out
    redirect_to new_admin_session_path
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_active,])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>nagano_cake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>

  <body class="d-flex flex-column vh-1">
    <header class="shadow-sm">
     <nav class="navbar navbar-expand-lg navbar-white bg-white p-4">
       <div class="container">
        <a class="navbar-brand" href="/">LOGO</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <% if customer_signed_in? %>
         <span class="offset-3">ようこそ、<%= current_customer.last_name %>さん！</span>
        <% end %>
         <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
           <% if admin_signed_in? %>
            <li class="nav-item p-3"><%= link_to '商品一覧', admin_items_path, class: 'btn btn-outline-secondary' %></li>
            <li class="nav-item p-3"><%= link_to '会員一覧', admin_customers_path, class: 'btn btn-outline-secondary' %></li>
            <li class="nav-item p-3"><%= link_to '注文履歴一覧', admin_root_path, class: 'btn btn-outline-secondary' %></li>
            <li class="nav-item p-3"><%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class: 'btn btn-outline-secondary' %></li>
           <% elsif customer_signed_in? %>
            <li class="nav-item p-2"><%= link_to 'マイページ', customers_my_page_path, class: 'btn btn-outline-secondary' %></li>
            <li class="nav-item p-2"><%= link_to '商品一覧', items_path, class: 'btn btn-outline-secondary' %></li>
            <li class="nav-item p-2"><%= link_to 'カート', cart_items_path, class: 'btn btn-outline-secondary' %></li>
            <li class="nav-item p-2"><%= link_to 'ログアウト', destroy_customer_session_path, method: :delete, class: 'btn btn-outline-secondary' %></li>
           <% else %>
            <li class="nav-item p-2"><%= link_to 'About', about_path, class: 'btn btn-outline-secondary' %></li>
            <li class="nav-item p-2"><%= link_to '商品一覧', items_path, class: 'btn btn-outline-secondary' %></li>
            <li class="nav-item p-2"><%= link_to '新規登録', new_customer_registration_path, class: 'btn btn-outline-secondary' %></li>
            <li class="nav-item p-2"><%= link_to 'ログイン', customer_session_path, class: 'btn btn-outline-secondary' %></li>
           <% end %>
         </ul>
        </div>
       </div>
      </nav>
    </header>
    <main>
      <% flash.each do |key, value| %>
       <%=content_tag(:div, value, class: "#{key}") %>
      <% end %>
      <%= yield %>
    </main>
    <footer class="footer text-white fixed-bottom p-2" style="background-color: white;">
     <div class="row">
      <div class="offset-8 mt-3">
       <p class="text footer-text"></p>
      </div>
     </div>
    </footer>
  </body>
</html>